# Generated by Django 5.2.7 on 2025-10-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_allergies_student_awards_student_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='awards',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='disciplinary_record',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='teacher',
            name='extra_curricular',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='genotype',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='teacher',
            name='health_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='home_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sports_house',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
