# Generated by Django 5.2.7 on 2025-10-27 15:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_delete_classlevel'),
        ('users', '0003_teacher_allergies_teacher_awards_teacher_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
            preserve_default=False,
        ),
    ]
