# Generated by Django 5.2.7 on 2025-10-27 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        ('schools', '0003_classlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlevel',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_classes', to='schools.school'),
        ),
    ]
