# Generated by Django 5.2.7 on 2025-10-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_classlevel_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlevel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
