# Generated by Django 5.2.7 on 2025-10-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_feestructure_studentfee'),
        ('schools', '0003_payment_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='school',
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='classlevel',
            unique_together={('name', 'school')},
        ),
    ]
