# Generated by Django 5.2.7 on 2025-10-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_classlevel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlevel',
            name='level',
            field=models.CharField(choices=[('primary_1', 'Primary 1'), ('primary_2', 'Primary 2'), ('primary_3', 'Primary 3'), ('primary_4', 'Primary 4'), ('primary_5', 'Primary 5'), ('primary_6', 'Primary 6'), ('jss_1', 'JSS 1'), ('jss_2', 'JSS 2'), ('jss_3', 'JSS 3'), ('ss_1', 'SS 1'), ('ss_2', 'SS 2'), ('ss_3', 'SS 3')], max_length=20),
        ),
    ]
