# Generated by Django 5.2.7 on 2025-10-28 15:03

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_classlevel_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentassignment',
            old_name='submitted_text',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='studentassignment',
            old_name='submitted_at',
            new_name='submission_date',
        ),
        migrations.AlterUniqueTogether(
            name='studentassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'zip'])]),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='submitted_file',
            field=models.FileField(blank=True, null=True, upload_to='submitted_assignments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'zip', 'jpg', 'png'])]),
        ),
    ]
