# Generated by Django 5.2.7 on 2025-10-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_result_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
