# Generated by Django 5.2.7 on 2025-10-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_classlevel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassLevel',
        ),
    ]
