# Generated by Django 5.2.7 on 2025-10-31 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={},
        ),
        migrations.AddField(
            model_name='school',
            name='about_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
